"""Pregenerates the boss's "radial" attack pattern into
src/boss_patterns_generated.h.

A table of (vx,vy) fix16 velocity pairs, evenly spaced around a full circle
and already scaled to RADIAL_SPEED -- so boss.c never has to call sin()/cos()
(or do any per-shot division/multiplication) at runtime, just spawn one
bullet per table entry using the value as-is (same reasoning as
res/generate_interwave.py's pregenerated weave paths).

Re-run after changing either constant below (RADIAL_SPEED must also be kept
in sync with boss.c's own copy -- see the comment there):
    python generate_boss_patterns.py
"""

import math
import os

# -- must match boss.c --
RADIAL_DIRECTION_COUNT = 10
RADIAL_SPEED = 1.4  # px/frame -- baked directly into each table entry below

OUT_PATH = os.path.join(os.path.dirname(__file__), "..", "src", "boss_patterns_generated.h")


def gen_directions(count, speed):
    directions = []
    for i in range(count):
        angle = 2 * math.pi * i / count
        vx = speed * math.cos(angle)
        vy = speed * math.sin(angle)
        directions.append((vx, vy))
    return directions


def emit_header(directions):
    lines = []
    lines.append("// AUTO-GENERATED by res/generate_boss_patterns.py -- do not edit directly;")
    lines.append("// re-run the generator instead.")
    lines.append("#ifndef BOSS_PATTERNS_GENERATED_H")
    lines.append("#define BOSS_PATTERNS_GENERATED_H")
    lines.append("")
    lines.append("#include \"game.h\"")
    lines.append("")
    lines.append(f"#define BOSS_RADIAL_DIRECTION_COUNT {len(directions)}")
    lines.append("")
    lines.append("// bossRadialVx/Vy[i] -- one bullet's velocity for the boss's \"radial\" attack")
    lines.append("// (see boss.c), already scaled to speed -- no runtime trig/div/mul needed,")
    lines.append("// just spawn a bullet with this exact (vx,vy) for each i.")
    lines.append("static const fix16 bossRadialVx[BOSS_RADIAL_DIRECTION_COUNT] =")
    lines.append("{")
    lines.append("    " + ", ".join(f"FIX16({vx:.6f})" for vx, _ in directions))
    lines.append("};")
    lines.append("")
    lines.append("static const fix16 bossRadialVy[BOSS_RADIAL_DIRECTION_COUNT] =")
    lines.append("{")
    lines.append("    " + ", ".join(f"FIX16({vy:.6f})" for _, vy in directions))
    lines.append("};")
    lines.append("")
    lines.append("#endif // BOSS_PATTERNS_GENERATED_H")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    directions = gen_directions(RADIAL_DIRECTION_COUNT, RADIAL_SPEED)

    header = emit_header(directions)
    with open(OUT_PATH, "w") as f:
        f.write(header)

    print(f"wrote {OUT_PATH} ({len(directions)} directions)")
