"""Pregenerates the boss's "radial" attack pattern into
src/boss_patterns_generated.h.

A table of (vx,vy) fix16 velocity pairs, evenly spaced around a full circle
and already scaled to RADIAL_SPEED -- so boss.c never has to call sin()/cos()
(or do any per-shot division/multiplication) at runtime, just spawn one
bullet per table entry using the value as-is (same reasoning as
res/generate_interwave.py's pregenerated weave paths).

Emits two variants -- NTSC and PAL -- since the whole game's timing assumes
50fps on PAL consoles vs 60fps on NTSC (see game.h's REGION_PICK): PAL's
RADIAL_SPEED is NTSC's * 1.2 so real-world (px/sec) bullet speed stays the
same; boss.c picks between the two tables at runtime via the same
REGION_PICK the rest of the game already uses, never recomputing anything.

Re-run after changing either constant below (RADIAL_SPEED_NTSC must also be
kept in sync with boss.c's own copy -- see the comment there):
    python generate_boss_patterns.py
"""

import math
import os

# -- must match boss.c --
RADIAL_DIRECTION_COUNT = 10
RADIAL_SPEED_NTSC = 1.4  # px/frame -- baked directly into each table entry below
RADIAL_SPEED_PAL = 1.68  # NTSC * 1.2, keeps real-world (px/sec) speed the same

OUT_PATH = os.path.join(os.path.dirname(__file__), "..", "src", "boss_patterns_generated.h")


def gen_directions(count, speed):
    directions = []
    for i in range(count):
        angle = 2 * math.pi * i / count
        vx = speed * math.cos(angle)
        vy = speed * math.sin(angle)
        directions.append((vx, vy))
    return directions


def emit_table(suffix, directions):
    lines = []
    lines.append(f"static const fix16 bossRadialVx{suffix}[BOSS_RADIAL_DIRECTION_COUNT] =")
    lines.append("{")
    lines.append("    " + ", ".join(f"FIX16({vx:.6f})" for vx, _ in directions))
    lines.append("};")
    lines.append("")
    lines.append(f"static const fix16 bossRadialVy{suffix}[BOSS_RADIAL_DIRECTION_COUNT] =")
    lines.append("{")
    lines.append("    " + ", ".join(f"FIX16({vy:.6f})" for _, vy in directions))
    lines.append("};")
    return lines


def emit_header(ntsc_directions, pal_directions):
    lines = []
    lines.append("// AUTO-GENERATED by res/generate_boss_patterns.py -- do not edit directly;")
    lines.append("// re-run the generator instead.")
    lines.append("#ifndef BOSS_PATTERNS_GENERATED_H")
    lines.append("#define BOSS_PATTERNS_GENERATED_H")
    lines.append("")
    lines.append("#include \"game.h\"")
    lines.append("")
    lines.append(f"#define BOSS_RADIAL_DIRECTION_COUNT {len(ntsc_directions)}")
    lines.append("")
    lines.append("// bossRadialVx/VyNtsc/Pal[i] -- one bullet's velocity for the boss's")
    lines.append("// \"radial\" attack (see boss.c), already scaled to speed -- no runtime")
    lines.append("// trig/div/mul needed, just spawn a bullet with this exact (vx,vy) for")
    lines.append("// each i. boss.c picks the pair matching the console's own region via")
    lines.append("// REGION_PICK (see game.h), same as every other dual NTSC/PAL constant.")
    lines.extend(emit_table("Ntsc", ntsc_directions))
    lines.append("")
    lines.extend(emit_table("Pal", pal_directions))
    lines.append("")
    lines.append("#endif // BOSS_PATTERNS_GENERATED_H")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    ntsc_directions = gen_directions(RADIAL_DIRECTION_COUNT, RADIAL_SPEED_NTSC)
    pal_directions = gen_directions(RADIAL_DIRECTION_COUNT, RADIAL_SPEED_PAL)

    header = emit_header(ntsc_directions, pal_directions)
    with open(OUT_PATH, "w") as f:
        f.write(header)

    print(f"wrote {OUT_PATH} ({len(ntsc_directions)} directions, NTSC + PAL)")
