"""Pregenerates random terrain/starfield "half bands" into src/terrain_generated.h.

terrain.c used to roll clump shapes and starfield stars at runtime, every
time a half of the scrolling plane needed to be varied -- cheap as a single
call, but each reroll meant thousands of random()+VDP_setTileMapXY calls
(one full clump/star scan per cell). Rolling a fixed set of variations here
instead, once, at build time, means terrain.c only has to pick one at random
and stamp its (small, precomputed) clump/star list -- no per-cell random()
calls left at runtime at all.

Re-run after changing any of the constants below (must also be kept in sync
with terrain.c's own copies -- see the comments there):
    python generate_terrain.py
"""

import os
import random

SEED = 20240521  # fixed, so regenerating without changing anything is a no-op

# -- must match terrain.c --
BAND_ROWS = 32               # PLANE_H_TILES / 2
VISIBLE_COLS = 40            # SCREEN_W / 8 -- columns past this never scroll into view
CLUMP_SPACING = 19  # must stay > CLUMP_MAX_SIZE (anchors packed as tight as that allows)
CLUMP_MAX_SIZE = 18
ANCHORS_PER_BAND = (VISIBLE_COLS + CLUMP_SPACING - 1) // CLUMP_SPACING
TERRAIN_BASE_TILE = 16       # TILE_USER_INDEX
STARFIELD_BASE_TILE = 32     # TILE_USER_INDEX + 16
PAL_TERRA = 3                # PAL3

TERRAIN_MAP_COUNT = 50
STARFIELD_MAP_COUNT = 50
STARFIELD_MAP_MAX_STARS = 128  # >5 stddev above the ~80 expected stars/band

OUT_PATH = os.path.join(os.path.dirname(__file__), "..", "src", "terrain_generated.h")


def gen_terrain_map(rnd):
    clumps = []
    for a in range(ANCHORS_PER_BAND):
        cx = a * CLUMP_SPACING

        if (rnd.getrandbits(4)) > 12:  # skip some anchors, but keep chunks fairly dense
            clumps.append(None)
            continue

        w = 1 + rnd.randrange(CLUMP_MAX_SIZE)
        h = 1 + rnd.randrange(CLUMP_MAX_SIZE)
        ox = min(cx + rnd.randrange(CLUMP_SPACING - w), VISIBLE_COLS - w)
        oy = rnd.randrange(BAND_ROWS - h)

        cells = [0] * (CLUMP_MAX_SIZE * CLUMP_MAX_SIZE)
        for dy in range(h):
            for dx in range(w):
                corner = (dx == 0 or dx == w - 1) and (dy == 0 or dy == h - 1)
                if corner and rnd.getrandbits(2) == 0:
                    continue  # leave as 0 (gap) -- irregular blob edges
                variant = rnd.getrandbits(2)  # 0..3
                cells[dy * w + dx] = variant + 1  # +1: 0 is reserved for "gap"

        clumps.append((ox, oy, w, h, cells))

    return clumps


def gen_starfield_map(rnd):
    stars = []
    for y in range(BAND_ROWS):
        for x in range(VISIBLE_COLS):
            roll = rnd.getrandbits(5)  # 0..31
            if roll == 0:
                stars.append((x, y, 1))
            elif roll == 1:
                stars.append((x, y, 2))

    if len(stars) > STARFIELD_MAP_MAX_STARS:
        raise ValueError(
            f"starfield map rolled {len(stars)} stars, exceeds "
            f"STARFIELD_MAP_MAX_STARS ({STARFIELD_MAP_MAX_STARS}) -- raise the cap"
        )

    return stars


def emit_header(terrainMaps, starfieldMaps):
    lines = []
    lines.append("// AUTO-GENERATED by res/generate_terrain.py -- do not edit directly;")
    lines.append("// re-run the generator instead.")
    lines.append("#ifndef TERRAIN_GENERATED_H")
    lines.append("#define TERRAIN_GENERATED_H")
    lines.append("")
    lines.append("#include \"game.h\"")
    lines.append("")
    lines.append(f"#define TERRAIN_MAP_BAND_ROWS {BAND_ROWS}")
    lines.append(f"#define TERRAIN_MAP_COLS      {VISIBLE_COLS}")
    lines.append(f"#define TERRAIN_MAP_ANCHORS   {ANCHORS_PER_BAND}")
    lines.append(f"#define TERRAIN_MAP_CLUMP_CELLS ({CLUMP_MAX_SIZE} * {CLUMP_MAX_SIZE})")
    lines.append(f"#define TERRAIN_MAP_COUNT     {TERRAIN_MAP_COUNT}")
    lines.append(f"#define STARFIELD_MAP_COUNT   {STARFIELD_MAP_COUNT}")
    lines.append(f"#define STARFIELD_MAP_MAX_STARS {STARFIELD_MAP_MAX_STARS}")
    lines.append("")
    lines.append("// tileW == 0 means this anchor rolled empty (see terrain.c).")
    lines.append("// cells[] is row-major within the tileW x tileH box (only the first")
    lines.append("// tileW*tileH entries are meaningful); 0 = gap, else tile variant + 1.")
    lines.append("typedef struct")
    lines.append("{")
    lines.append("    u8 tileX, tileY, tileW, tileH;")
    lines.append("    u8 cells[TERRAIN_MAP_CLUMP_CELLS];")
    lines.append("} TerrainMapClump;")
    lines.append("")
    lines.append("typedef struct")
    lines.append("{")
    lines.append("    TerrainMapClump clumps[TERRAIN_MAP_ANCHORS];")
    lines.append("} TerrainMap;")
    lines.append("")
    lines.append("typedef struct")
    lines.append("{")
    lines.append("    u8 x, y, variant; // variant: 1 or 2 (see STARFIELD_BASE_TILE)")
    lines.append("} StarfieldStar;")
    lines.append("")
    lines.append("typedef struct")
    lines.append("{")
    lines.append("    u16 count;")
    lines.append("    StarfieldStar stars[STARFIELD_MAP_MAX_STARS];")
    lines.append("} StarfieldMap;")
    lines.append("")

    lines.append("static const TerrainMap terrainMaps[TERRAIN_MAP_COUNT] =")
    lines.append("{")
    for clumps in terrainMaps:
        lines.append("    {{")
        for c in clumps:
            if c is None:
                lines.append("        { 0, 0, 0, 0, {0} },")
            else:
                ox, oy, w, h, cells = c
                cell_str = ", ".join(str(v) for v in cells)
                lines.append(f"        {{ {ox}, {oy}, {w}, {h}, {{{cell_str}}} }},")
        lines.append("    }},")
    lines.append("};")
    lines.append("")

    lines.append("static const StarfieldMap starfieldMaps[STARFIELD_MAP_COUNT] =")
    lines.append("{")
    for stars in starfieldMaps:
        padded = list(stars) + [(0, 0, 0)] * (STARFIELD_MAP_MAX_STARS - len(stars))
        star_str = ", ".join(f"{{{x}, {y}, {v}}}" for x, y, v in padded)
        lines.append(f"    {{ {len(stars)}, {{{star_str}}} }},")
    lines.append("};")
    lines.append("")
    lines.append("#endif // TERRAIN_GENERATED_H")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    rnd = random.Random(SEED)

    terrainMaps = [gen_terrain_map(rnd) for _ in range(TERRAIN_MAP_COUNT)]
    starfieldMaps = [gen_starfield_map(rnd) for _ in range(STARFIELD_MAP_COUNT)]

    header = emit_header(terrainMaps, starfieldMaps)
    with open(OUT_PATH, "w") as f:
        f.write(header)

    print(f"wrote {OUT_PATH} ({TERRAIN_MAP_COUNT} terrain maps, {STARFIELD_MAP_COUNT} starfield maps)")
