"""Pregenerates the 4 inter-wave "waver" movement paths into src/interwave_generated.h.

Each path is a table of s16 x-offsets (pixels from the batch's own
horizontal center), sampled once per frame across the whole flight -- so
enemy.c never has to call sin() on the 68000 at runtime, just look up a
table entry (same reasoning as res/generate_terrain.py's pregenerated
clumps/stars). Path choice is independent of ENEMY_KIND_WAVER_A/B/C (which
only pick the sprite/color) -- enemy.c's spawnNextWaverSubgroup() picks one
of these WAVER_PATH_COUNT paths at random (via random(), so it's
deterministic given the game's PRNG state, not truly unpredictable) each
time a batch spawns.

Re-run after changing any of the constants below (must also be kept in sync
with enemy.c's own copies -- see the comments there):
    python generate_interwave.py
"""

import math
import os

# -- must match enemy.c --
SCREEN_H = 224
SPRITE_H = 16
DESCEND_SPEED_PX = 1.5  # matches WAVER_DESCEND_SPEED (fix16) in enemy.c

# Frames to fully traverse from just above the screen to just below it --
# rounded up a bit past the exact crossing so a sub-block is unmistakably
# gone (see enemies_update()'s "y > SCREEN_H" deactivate check) before its
# table could run out.
PATH_LENGTH = int((SCREEN_H + 2 * SPRITE_H) / DESCEND_SPEED_PX) + 16

# (amplitude1_px, cycles1_over_flight, amplitude2_px, cycles2_over_flight) --
# one per path variant, chosen so each reads as visually distinct in motion.
# The second (amplitude, cycles) pair layers a second sine on top of the
# first -- 0 amplitude means "just a plain single sine" for the simpler
# variants. Phase is deliberately always 0 for every component (not a
# tunable here): a batch goes straight from spawn into this path at whatever
# frame currentWaverClock is already at (see enemy.c's ENEMY_STATE_WAVING),
# and every component must start at x-offset 0 or that could show as a
# sudden sideways jump the moment a member is revealed.
PATHS = [
    (35, 1.25, 0, 0),   # wide, energetic weave
    (45, 2.25, 0, 0),   # tighter, faster weave
    (28, 3.5, 0, 0),    # quick, snappy weave
    (30, 1.0, 10, 3.0), # wobble -- slow wide primary + faster small secondary
]

OUT_PATH = os.path.join(os.path.dirname(__file__), "..", "src", "interwave_generated.h")


def gen_path(amplitude1, cycles1, amplitude2, cycles2):
    values = []
    for t in range(PATH_LENGTH):
        angle1 = 2 * math.pi * cycles1 * t / PATH_LENGTH
        angle2 = 2 * math.pi * cycles2 * t / PATH_LENGTH
        v = amplitude1 * math.sin(angle1) + amplitude2 * math.sin(angle2)
        values.append(int(round(v)))
    return values


def emit_header(paths):
    lines = []
    lines.append("// AUTO-GENERATED by res/generate_interwave.py -- do not edit directly;")
    lines.append("// re-run the generator instead.")
    lines.append("#ifndef INTERWAVE_GENERATED_H")
    lines.append("#define INTERWAVE_GENERATED_H")
    lines.append("")
    lines.append("#include \"game.h\"")
    lines.append("")
    lines.append(f"#define WAVER_PATH_COUNT  {len(paths)}")
    lines.append(f"#define WAVER_PATH_LENGTH {PATH_LENGTH}")
    lines.append("")
    lines.append("// waverPaths[pathId][frame] -- x-offset in pixels from the sub-block's own")
    lines.append("// horizontal center at that frame of its flight (see enemy.c's")
    lines.append("// ENEMY_STATE_WAVING). Index with the sub-block's own clock, clamped to")
    lines.append("// WAVER_PATH_LENGTH-1 (it'll already be off screen and deactivated well")
    lines.append("// before running past the end -- see WAVER_DESCEND_SPEED).")
    lines.append(f"static const s16 waverPaths[WAVER_PATH_COUNT][WAVER_PATH_LENGTH] =")
    lines.append("{")
    for values in paths:
        value_str = ", ".join(str(v) for v in values)
        lines.append(f"    {{{value_str}}},")
    lines.append("};")
    lines.append("")
    lines.append("#endif // INTERWAVE_GENERATED_H")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    paths = [gen_path(*p) for p in PATHS]

    header = emit_header(paths)
    with open(OUT_PATH, "w") as f:
        f.write(header)

    print(f"wrote {OUT_PATH} ({len(paths)} paths, {PATH_LENGTH} frames each)")
