"""Pregenerates the 4 inter-wave "waver" movement paths into src/interwave_generated.h.

Each path is a table of s16 x-offsets (pixels from the batch's own
horizontal center), sampled once per frame across the whole flight -- so
enemy.c never has to call sin() on the 68000 at runtime, just look up a
table entry (same reasoning as res/generate_terrain.py's pregenerated
clumps/stars). Path choice is independent of ENEMY_KIND_WAVER_A/B/C (which
only pick the sprite/color) -- enemy.c's spawnNextWaverSubgroup() picks one
of these WAVER_PATH_COUNT paths at random (via random(), so it's
deterministic given the game's PRNG state, not truly unpredictable) each
time a batch spawns.

Emits two variants -- NTSC and PAL -- since the whole game's timing assumes
50fps on PAL consoles vs 60fps on NTSC (see game.h's REGION_PICK): PAL's
DESCEND_SPEED_PX is NTSC's * 1.2 so real-world (px/sec) descent speed stays
the same, which in turn makes PAL's PATH_LENGTH shorter (fewer frames to
cross the same screen height at a faster per-frame speed) -- enemy.c picks
between the two tables at runtime via the same REGION_PICK the rest of the
game already uses, never recomputing anything.

Re-run after changing any of the constants below (must also be kept in sync
with enemy.c's own copies -- see the comments there):
    python generate_interwave.py
"""

import math
import os

# -- must match enemy.c --
SCREEN_H = 224
SPRITE_H = 16
DESCEND_SPEED_PX_NTSC = 1.5  # matches WAVER_DESCEND_SPEED's NTSC value (fix16) in enemy.c
DESCEND_SPEED_PX_PAL = 1.8   # matches WAVER_DESCEND_SPEED's PAL value (fix16) in enemy.c -- NTSC * 1.2

# (amplitude1_px, cycles1_over_flight, amplitude2_px, cycles2_over_flight) --
# one per path variant, chosen so each reads as visually distinct in motion.
# The second (amplitude, cycles) pair layers a second sine on top of the
# first -- 0 amplitude means "just a plain single sine" for the simpler
# variants. Phase is deliberately always 0 for every component (not a
# tunable here): a batch goes straight from spawn into this path at whatever
# frame currentWaverClock is already at (see enemy.c's ENEMY_STATE_WAVING),
# and every component must start at x-offset 0 or that could show as a
# sudden sideways jump the moment a member is revealed. "cycles_over_flight"
# is independent of frame rate -- it's how many wave cycles happen across
# the whole (region-specific) PATH_LENGTH, so the same PATHS list produces
# the same visual shape for both regions, just sampled at a different rate.
PATHS = [
    (35, 1.25, 0, 0),   # wide, energetic weave
    (45, 2.25, 0, 0),   # tighter, faster weave
    (28, 3.5, 0, 0),    # quick, snappy weave
    (30, 1.0, 10, 3.0), # wobble -- slow wide primary + faster small secondary
]

OUT_PATH = os.path.join(os.path.dirname(__file__), "..", "src", "interwave_generated.h")


def path_length(descend_speed_px):
    # Frames to fully traverse from just above the screen to just below it --
    # rounded up a bit past the exact crossing so a sub-block is unmistakably
    # gone (see enemies_update()'s "y > SCREEN_H" deactivate check) before its
    # table could run out.
    return int((SCREEN_H + 2 * SPRITE_H) / descend_speed_px) + 16


def gen_path(length, amplitude1, cycles1, amplitude2, cycles2):
    values = []
    for t in range(length):
        angle1 = 2 * math.pi * cycles1 * t / length
        angle2 = 2 * math.pi * cycles2 * t / length
        v = amplitude1 * math.sin(angle1) + amplitude2 * math.sin(angle2)
        values.append(int(round(v)))
    return values


def emit_table(name, length_macro, length, paths):
    lines = []
    lines.append(f"#define {length_macro} {length}")
    lines.append(f"static const s16 {name}[WAVER_PATH_COUNT][{length_macro}] =")
    lines.append("{")
    for values in paths:
        value_str = ", ".join(str(v) for v in values)
        lines.append(f"    {{{value_str}}},")
    lines.append("};")
    return lines


def emit_header(ntsc_length, ntsc_paths, pal_length, pal_paths):
    lines = []
    lines.append("// AUTO-GENERATED by res/generate_interwave.py -- do not edit directly;")
    lines.append("// re-run the generator instead.")
    lines.append("#ifndef INTERWAVE_GENERATED_H")
    lines.append("#define INTERWAVE_GENERATED_H")
    lines.append("")
    lines.append("#include \"game.h\"")
    lines.append("")
    lines.append(f"#define WAVER_PATH_COUNT  {len(PATHS)}")
    lines.append("")
    lines.append("// waverPathsNtsc/Pal[pathId][frame] -- x-offset in pixels from the")
    lines.append("// sub-block's own horizontal center at that frame of its flight (see")
    lines.append("// enemy.c's ENEMY_STATE_WAVING). Index with the sub-block's own clock,")
    lines.append("// clamped to WAVER_PATH_LENGTH_NTSC/PAL-1 (it'll already be off screen and")
    lines.append("// deactivated well before running past the end -- see WAVER_DESCEND_SPEED).")
    lines.append("// enemy.c picks the table/length matching the console's own region via")
    lines.append("// REGION_PICK (see game.h), same as every other dual NTSC/PAL constant.")
    lines.extend(emit_table("waverPathsNtsc", "WAVER_PATH_LENGTH_NTSC", ntsc_length, ntsc_paths))
    lines.append("")
    lines.extend(emit_table("waverPathsPal", "WAVER_PATH_LENGTH_PAL", pal_length, pal_paths))
    lines.append("")
    lines.append("#endif // INTERWAVE_GENERATED_H")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    ntsc_length = path_length(DESCEND_SPEED_PX_NTSC)
    pal_length = path_length(DESCEND_SPEED_PX_PAL)
    ntsc_paths = [gen_path(ntsc_length, *p) for p in PATHS]
    pal_paths = [gen_path(pal_length, *p) for p in PATHS]

    header = emit_header(ntsc_length, ntsc_paths, pal_length, pal_paths)
    with open(OUT_PATH, "w") as f:
        f.write(header)

    print(f"wrote {OUT_PATH} ({len(PATHS)} paths, {ntsc_length} NTSC / {pal_length} PAL frames each)")
