"""Parses res/waves.txt into src/waves_generated.h for SGDK/formation.c.

The Genesis has no runtime filesystem, so waves.txt can't be read by the
game itself -- this script converts it into a C header compiled directly
into the ROM, the same build-time-generation pattern res/gfx's
generate_placeholders.py uses for art. Re-run after editing waves.txt:
    python generate_waves.py
"""

import os

MAX_ENEMIES = 30  # must match src/game.h's MAX_ENEMIES
MAX_SPECIALS_PER_WAVE = 8

SRC_PATH = os.path.join(os.path.dirname(__file__), "waves.txt")
OUT_PATH = os.path.join(os.path.dirname(__file__), "..", "src", "waves_generated.h")


def parse_waves(text):
    waves = []
    current = None
    wave_number = None

    for lineno, raw_line in enumerate(text.splitlines(), start=1):
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue

        parts = line.split()
        cmd = parts[0]

        if cmd == "wave":
            if current is not None:
                waves.append(current)
            wave_number = int(parts[1])
            current = {"number": wave_number, "big": 0, "rows": 0, "cols": 0, "specials": []}
        elif cmd == "big":
            current["big"] = int(parts[1])
        elif cmd == "grid":
            current["rows"] = int(parts[1])
            current["cols"] = int(parts[2])
        elif cmd == "special":
            current["specials"].append((int(parts[1]), int(parts[2])))
        else:
            raise ValueError(f"waves.txt:{lineno}: unknown directive '{cmd}'")

    if current is not None:
        waves.append(current)

    return waves


def validate(wave):
    n = wave["number"]
    total = wave["big"] + wave["rows"] * wave["cols"]
    if total > MAX_ENEMIES:
        raise ValueError(
            f"wave {n}: big({wave['big']}) + grid({wave['rows']}x{wave['cols']}) = "
            f"{total} enemies, exceeds MAX_ENEMIES ({MAX_ENEMIES})"
        )
    if len(wave["specials"]) > MAX_SPECIALS_PER_WAVE:
        raise ValueError(
            f"wave {n}: {len(wave['specials'])} 'special' entries, "
            f"exceeds MAX_SPECIALS_PER_WAVE ({MAX_SPECIALS_PER_WAVE})"
        )
    for row, col in wave["specials"]:
        if not (0 <= row < wave["rows"] and 0 <= col < wave["cols"]):
            raise ValueError(f"wave {n}: special ({row},{col}) is outside the {wave['rows']}x{wave['cols']} grid")


def emit_header(waves):
    lines = []
    lines.append("// AUTO-GENERATED by res/generate_waves.py from res/waves.txt -- do not edit")
    lines.append("// directly; re-run the generator instead.")
    lines.append("#ifndef WAVES_GENERATED_H")
    lines.append("#define WAVES_GENERATED_H")
    lines.append("")
    lines.append("#include \"game.h\"")
    lines.append("")
    lines.append(f"#define MAX_SPECIALS_PER_WAVE {MAX_SPECIALS_PER_WAVE}")
    lines.append("")
    lines.append("typedef struct")
    lines.append("{")
    lines.append("    u8 bigCount;")
    lines.append("    u8 gridRows;")
    lines.append("    u8 gridCols;")
    lines.append("    u8 specialCount;")
    lines.append("    u8 specialRow[MAX_SPECIALS_PER_WAVE];")
    lines.append("    u8 specialCol[MAX_SPECIALS_PER_WAVE];")
    lines.append("} WaveDef;")
    lines.append("")
    lines.append(f"#define WAVE_COUNT {len(waves)}")
    lines.append("")
    lines.append("static const WaveDef waves[WAVE_COUNT] =")
    lines.append("{")
    for wave in waves:
        specials = wave["specials"]
        rows = ", ".join(str(r) for r, _ in specials) or "0"
        cols = ", ".join(str(c) for _, c in specials) or "0"
        pad_rows = ", ".join(["0"] * (MAX_SPECIALS_PER_WAVE - len(specials)))
        pad_cols = ", ".join(["0"] * (MAX_SPECIALS_PER_WAVE - len(specials)))
        row_list = rows + (", " + pad_rows if pad_rows else "")
        col_list = cols + (", " + pad_cols if pad_cols else "")
        lines.append(
            f"    // wave {wave['number']}"
        )
        lines.append(
            f"    {{ {wave['big']}, {wave['rows']}, {wave['cols']}, {len(specials)}, "
            f"{{{row_list}}}, {{{col_list}}} }},"
        )
    lines.append("};")
    lines.append("")
    lines.append("#endif // WAVES_GENERATED_H")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    with open(SRC_PATH, "r") as f:
        text = f.read()

    waves = parse_waves(text)
    if not waves:
        raise SystemExit("waves.txt defines no waves")

    for wave in waves:
        validate(wave)

    header = emit_header(waves)
    with open(OUT_PATH, "w") as f:
        f.write(header)

    print(f"wrote {OUT_PATH} ({len(waves)} waves)")
