"""Derives pixel hit masks from *existing* sprite art for kinds whose AABB
has large, consistently transparent regions -- see collision.c's comments on
why only these kinds get a mask instead of relying on their AABB alone:
ENEMY_KIND_BIG (blocky "capital ship") and the 5 boss kinds' bodies
(irregular hulls: diamond/saucer/round/spike/wing -- see boss.c's BossDef
roster). Weak-spot pods stay AABB-only -- close enough to their round art
that a mask wouldn't change the outcome.

This script only ever *reads* PNGs, never writes them (unlike
generate_placeholders.py) -- safe to run over hand-edited art without risk
of clobbering it.

Re-run after editing enemy_big.png's or any boss_body_*.png's silhouette:
    python generate_hitmasks.py
"""

import os

from PIL import Image

GFX_DIR = os.path.dirname(__file__)
OUT_DIR = os.path.join(GFX_DIR, "..", "..", "src")

BOSS_SUFFIXES = ["a", "b", "c", "d", "e"]  # must match boss.h's BossKind order (BOSS_KIND_A..E)

BOSS_QUAD_SIZE = 32   # boss.c's BOSS_QUAD_W/H
BOSS_BODY_SIZE = 64   # boss.c's BOSS_BODY_W/H
BIG_SIZE = 32         # enemy_widthForKind(ENEMY_KIND_BIG)


def load_indexed(path, expect_w):
    img = Image.open(path)
    if img.mode != "P":
        raise SystemExit(f"{path}: expected palette ('P') mode, got {img.mode}")
    w, _ = img.size
    if w != expect_w:
        raise SystemExit(f"{path}: expected {expect_w}px wide, got {w}")
    return img


def solid(img, x, y):
    return img.getpixel((x, y)) != 0  # index 0 == transparent, see generate_placeholders.py


def build_enemy_big_mask():
    # Sprite sheet is 2 stacked BIG_SIZE-tall frames (normal, hit-flash) --
    # see generate_placeholders.py's _enemy_frames(). Both share the exact
    # same silhouette, so only the top (normal) frame is read here.
    img = load_indexed(os.path.join(GFX_DIR, "enemy_big.png"), BIG_SIZE)
    rows = []
    for y in range(BIG_SIZE):
        bits = 0
        for x in range(BIG_SIZE):
            if solid(img, x, y):
                bits |= 1 << x  # bit x (0 = leftmost column)
        rows.append(bits)
    return rows


def build_boss_body_mask(suffix):
    # 32-wide, 64-tall sheet: rows [0,32) = TL quadrant, rows [32,64) = BL
    # quadrant -- together the body's left half (see boss.c's boss_begin(),
    # which draws these two as-is and the right half as their horizontal
    # mirror via TILE_ATTR_FULL's hflip). Mirroring is baked in here so
    # runtime never needs to do it: maskHi[y] bit (x-32) = left-half pixel
    # at column (63-x), matching hflip's column-reversal-within-the-tile.
    img = load_indexed(os.path.join(GFX_DIR, f"boss_body_{suffix}.png"), BOSS_QUAD_SIZE)

    def left_pixel(x, y):
        if y < BOSS_QUAD_SIZE:
            return solid(img, x, y)
        return solid(img, x, y - BOSS_QUAD_SIZE)

    maskLo = []
    maskHi = []
    for y in range(BOSS_BODY_SIZE):
        lo = 0
        for x in range(BOSS_QUAD_SIZE):
            if left_pixel(x, y):
                lo |= 1 << x
        hi = 0
        for x in range(BOSS_QUAD_SIZE, BOSS_BODY_SIZE):
            if left_pixel(BOSS_BODY_SIZE - 1 - x, y):
                hi |= 1 << (x - BOSS_QUAD_SIZE)
        maskLo.append(lo)
        maskHi.append(hi)
    return maskLo, maskHi


def emit_enemy_big_header(rows):
    lines = []
    lines.append("// AUTO-GENERATED by res/gfx/generate_hitmasks.py from enemy_big.png --")
    lines.append("// do not edit directly; re-run the generator after changing that art.")
    lines.append("#ifndef ENEMY_BIG_MASK_GENERATED_H")
    lines.append("#define ENEMY_BIG_MASK_GENERATED_H")
    lines.append("")
    lines.append("#include \"game.h\"")
    lines.append("")
    lines.append(f"#define ENEMY_BIG_MASK_SIZE {BIG_SIZE}")
    lines.append("")
    lines.append("// One u32 per row, bit x (0 = leftmost column) set if that pixel is solid")
    lines.append("// (non-transparent) -- see enemy_hitTestPixel() in enemy.c.")
    lines.append("static const u32 enemyBigMask[ENEMY_BIG_MASK_SIZE] =")
    lines.append("{")
    for bits in rows:
        lines.append(f"    0x{bits:08X},")
    lines.append("};")
    lines.append("")
    lines.append("#endif // ENEMY_BIG_MASK_GENERATED_H")
    lines.append("")
    return "\n".join(lines)


def emit_boss_header(bodyMasks):
    lines = []
    lines.append("// AUTO-GENERATED by res/gfx/generate_hitmasks.py from boss_body_*.png --")
    lines.append("// do not edit directly; re-run the generator after changing that art.")
    lines.append("#ifndef BOSS_MASK_GENERATED_H")
    lines.append("#define BOSS_MASK_GENERATED_H")
    lines.append("")
    lines.append("#include \"game.h\"")
    lines.append("")
    lines.append(f"#define BOSS_MASK_KIND_COUNT {len(BOSS_SUFFIXES)}")
    lines.append(f"#define BOSS_BODY_MASK_SIZE {BOSS_BODY_SIZE}")
    lines.append("")
    lines.append("// Indexed [BossKind][row]. Columns 0-31 in bodyMaskLo, 32-63 (bit x-32) in")
    lines.append("// bodyMaskHi -- the right half is already mirrored in here (see")
    lines.append("// build_boss_body_mask()), so boss.c never has to hflip at runtime.")
    lines.append("static const u32 bossBodyMaskLo[BOSS_MASK_KIND_COUNT][BOSS_BODY_MASK_SIZE] =")
    lines.append("{")
    for lo, _ in bodyMasks:
        row_str = ", ".join(f"0x{v:08X}" for v in lo)
        lines.append(f"    {{{row_str}}},")
    lines.append("};")
    lines.append("")
    lines.append("static const u32 bossBodyMaskHi[BOSS_MASK_KIND_COUNT][BOSS_BODY_MASK_SIZE] =")
    lines.append("{")
    for _, hi in bodyMasks:
        row_str = ", ".join(f"0x{v:08X}" for v in hi)
        lines.append(f"    {{{row_str}}},")
    lines.append("};")
    lines.append("")
    lines.append("#endif // BOSS_MASK_GENERATED_H")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    bigRows = build_enemy_big_mask()
    with open(os.path.join(OUT_DIR, "enemy_big_mask_generated.h"), "w") as f:
        f.write(emit_enemy_big_header(bigRows))
    solid_px = sum(bin(r).count("1") for r in bigRows)
    print(f"wrote enemy_big_mask_generated.h ({solid_px}/{BIG_SIZE * BIG_SIZE} px solid, {100 * solid_px // (BIG_SIZE * BIG_SIZE)}%)")

    bodyMasks = [build_boss_body_mask(s) for s in BOSS_SUFFIXES]
    with open(os.path.join(OUT_DIR, "boss_mask_generated.h"), "w") as f:
        f.write(emit_boss_header(bodyMasks))
    for suffix, (lo, hi) in zip(BOSS_SUFFIXES, bodyMasks):
        solid_px = sum(bin(v).count("1") for v in lo) + sum(bin(v).count("1") for v in hi)
        total_px = BOSS_BODY_SIZE * BOSS_BODY_SIZE
        print(f"  kind {suffix}: body {solid_px}/{total_px} px solid ({100 * solid_px // total_px}%)")
    print(f"wrote boss_mask_generated.h ({len(BOSS_SUFFIXES)} kinds)")
