// AUTO-GENERATED by res/generate_boss_patterns.py -- do not edit directly;
// re-run the generator instead.
#ifndef BOSS_PATTERNS_GENERATED_H
#define BOSS_PATTERNS_GENERATED_H

#include "game.h"

#define BOSS_RADIAL_DIRECTION_COUNT 10

// bossRadialVx/Vy[i] -- one bullet's velocity for the boss's "radial" attack
// (see boss.c), already scaled to speed -- no runtime trig/div/mul needed,
// just spawn a bullet with this exact (vx,vy) for each i.
static const fix16 bossRadialVx[BOSS_RADIAL_DIRECTION_COUNT] =
{
    FIX16(1.400000), FIX16(1.132624), FIX16(0.432624), FIX16(-0.432624), FIX16(-1.132624), FIX16(-1.400000), FIX16(-1.132624), FIX16(-0.432624), FIX16(0.432624), FIX16(1.132624)
};

static const fix16 bossRadialVy[BOSS_RADIAL_DIRECTION_COUNT] =
{
    FIX16(0.000000), FIX16(0.822899), FIX16(1.331479), FIX16(1.331479), FIX16(0.822899), FIX16(0.000000), FIX16(-0.822899), FIX16(-1.331479), FIX16(-1.331479), FIX16(-0.822899)
};

#endif // BOSS_PATTERNS_GENERATED_H
