// AUTO-GENERATED by res/gfx/generate_hitmasks.py from enemy_big.png --
// do not edit directly; re-run the generator after changing that art.
#ifndef ENEMY_BIG_MASK_GENERATED_H
#define ENEMY_BIG_MASK_GENERATED_H

#include "game.h"

#define ENEMY_BIG_MASK_SIZE 32

// One u32 per row, bit x (0 = leftmost column) set if that pixel is solid
// (non-transparent) -- see enemy_hitTestPixel() in enemy.c.
static const u32 enemyBigMask[ENEMY_BIG_MASK_SIZE] =
{
    0x00000000,
    0x00018000,
    0x0003C000,
    0x0007E000,
    0x0007E000,
    0x000FF000,
    0x000FF000,
    0x001FF800,
    0x001FF800,
    0x001FF800,
    0x003FFC00,
    0x003FFC00,
    0x003FFC00,
    0x007FFE00,
    0x067FFE60,
    0x0F7FFEF0,
    0x1FBFFDF8,
    0x1F7FFEF8,
    0x3FFFFFFC,
    0x3FFFFFFC,
    0x3FFFFFFC,
    0x3CFFFF3C,
    0x3C7FFE3C,
    0x3C77EE3C,
    0x1C624E38,
    0x1E000078,
    0x0E000070,
    0x0E000070,
    0x06000060,
    0x00000000,
    0x00000000,
    0x00000000,
};

#endif // ENEMY_BIG_MASK_GENERATED_H
