// AUTO-GENERATED by res/generate_waves.py from res/waves.txt -- do not edit
// directly; re-run the generator instead.
#ifndef WAVES_GENERATED_H
#define WAVES_GENERATED_H

#include "game.h"

#define MAX_SPECIALS_PER_WAVE 8

typedef struct
{
    u8 bigCount;
    u8 gridRows;
    u8 gridCols;
    u8 specialCount;
    u8 specialRow[MAX_SPECIALS_PER_WAVE];
    u8 specialCol[MAX_SPECIALS_PER_WAVE];
} WaveDef;

#define WAVE_COUNT 10

static const WaveDef waves[WAVE_COUNT] =
{
    // wave 1
    { 1, 3, 5, 1, {1, 0, 0, 0, 0, 0, 0, 0}, {2, 0, 0, 0, 0, 0, 0, 0} },
    // wave 2
    { 2, 3, 6, 2, {0, 2, 0, 0, 0, 0, 0, 0}, {1, 4, 0, 0, 0, 0, 0, 0} },
    // wave 3
    { 2, 4, 5, 3, {0, 1, 3, 0, 0, 0, 0, 0}, {0, 4, 2, 0, 0, 0, 0, 0} },
    // wave 4
    { 3, 4, 5, 4, {0, 2, 2, 3, 0, 0, 0, 0}, {2, 0, 4, 2, 0, 0, 0, 0} },
    // wave 5
    { 3, 4, 6, 2, {0, 2, 0, 0, 0, 0, 0, 0}, {1, 4, 0, 0, 0, 0, 0, 0} },
    // wave 6
    { 3, 4, 6, 4, {0, 0, 2, 3, 0, 0, 0, 0}, {0, 5, 2, 4, 0, 0, 0, 0} },
    // wave 7
    { 4, 4, 5, 3, {1, 1, 3, 0, 0, 0, 0, 0}, {0, 4, 2, 0, 0, 0, 0, 0} },
    // wave 8
    { 4, 3, 6, 5, {0, 0, 0, 2, 2, 0, 0, 0}, {0, 3, 5, 1, 4, 0, 0, 0} },
    // wave 9
    { 4, 4, 6, 5, {0, 0, 1, 2, 3, 0, 0, 0}, {0, 3, 5, 0, 2, 0, 0, 0} },
    // wave 10
    { 4, 4, 6, 6, {0, 0, 0, 1, 2, 3, 0, 0}, {0, 2, 4, 1, 3, 5, 0, 0} },
};

#endif // WAVES_GENERATED_H
